### ISSUE TITLE
Fronius Primo 8.2-1

### ISSUE THREAD

**Issue by MrBretze** [redpomodoro/fronius_modbus#7]
**Describe the issue you are experiencing**
Hello, i have a fronius primo 8.2-1 and i can't connect to this one
its say "unsupported_hardware"

**Describe the expected behavior**
The support of this one ?

**To Reproduce**
1. Go to "add integration"
2. Search "Fronius modbus"
3. Configure with the ip of the inverter
4. see the error: "unsupported_hardware"

**What version of Home Assistant Core is installed**
2024.12.4

**What version of Fronius Modbus integration is installed**
Release 0.1.1

**What Inverter and extras are you using**
Primo 8.2-1  
Smart Meter TS 100A-1
Battery System: No battery

**Error message shown within Home Assistant log**
none

**Diagnostics information of Fronius Modbus integration**
Not possible because i cant configure this integration

**Screenshots**
![image](https://github.com/user-attachments/assets/b9320933-1ea3-4eff-ae01-a7099d2eb033)

**Comment by redpomodoro** [comment]
The integration has been only tested with Gen24 inverters; however I will disable the check for Gen24 inverters and will allow all Fronius inverters so we can see if they will work too. Will be added in the next release.

**Comment by redpomodoro** [comment]
This has been released in v0.1.2

**Comment by gonzalezcalleja** [comment]
Tested with Primo 8.2-1 doesn't show some values for some sensors like MPPT Power:

<img width="329" alt="Image" src="https://github.com/user-attachments/assets/228fff30-af4a-444c-b8f8-5bcb2270c4d9" />

It would be great to have support for all primo sensors, thanks for your support!

**Comment by gonzalezcalleja** [comment]
> Added AC life time energy and AC power for systems without mppt. In the next version the mppt datapoints will only be added if the inverter supports it.

Thanks! Primo 8.2-1 doesn't support MPPT metrics by MODBUS? My device has 2 MPPTs.

**Comment by redpomodoro** [comment]
Is your inverter using 2 strings or 1 string? 

Maybe it only provides data in the mppt data fields in case multiple strings and/or storage device is used.

**Comment by laasfuus** [comment]
I just installed Fronius Symo 8.2-3-M with panels in 2 strings. I have same sensors unavailable.

Is there some way I can get required datafields/mappings for you to add support?

**Comment by MikeHotel0815** [comment]
![Image](https://github.com/user-attachments/assets/a7e79729-802c-49ff-b0c3-33bbca0a6a2e)

Same here for a "Fronius Symo 10.0-3-M". MPPT and MPPT2 is "missing"

**Comment by iz8azz** [comment]
### @redpomodoro  
Hi, same here for a Primo 6.0-1 .
2 strings, in inverter menu I can read both strings values, I read distinct values ( Mppt0 A,V,W - Mppt1 A,V,W) 
in sunspec integration, but it misses other values like day generation and others. 
Have some errors in log : 

```
Registratore: custom_components.fronius_modbus.extmodbusclient
Fonte: custom_components/fronius_modbus/extmodbusclient.py:255
Integrazione: Fronius Modbus (documentazione, problemi)
Prima occorrenza: 01:47:07 (309 occorrenze)
Ultimo accesso: 01:55:48
calculated value: -327.7 below lower bound 0 value: -32768 sf: -2 digits 1

```


second one maybe related to late night test :

edit: no , unrelated to test in night time


```
Registratore: custom_components.fronius_modbus.hub
Fonte: custom_components/fronius_modbus/hub.py:151
Integrazione: Fronius Modbus (documentazione, problemi)
Prima occorrenza: 01:47:05 (103 occorrenze)
Ultimo accesso: 01:55:45
Error reading inverter status data
Traceback (most recent call last):
  File "/config/custom_components/fronius_modbus/hub.py", line 151, in async_refresh_modbus_data
    update_result = await self._client.read_inverter_status_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fronius_modbus/froniusmodbusclient.py", line 249, in read_inverter_status_data
    self.data['pv_connection'] = CONNECTION_STATUS_CONDENSED[PVConn]
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 6

```
